steps:
  # --- 1. Build the PROXY image ---
  # Using the new mirrored builder path
  - name: "mirror.gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/automigrate-proxy:$SHORT_SHA"
      - "-f"
      - "docker/Dockerfile.proxy" # Fixed case
      - "."

  # --- 2. Build the LEGACY image ---
  # Using the new mirrored builder path
  - name: "mirror.gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/automigrate-legacy:$SHORT_SHA"
      - "-f"
      - "docker/Dockerfile.legacy" # Fixed case
      - "."

  # --- 3. Build the CLOUD image ---
  # Using the new mirrored builder path
  - name: "mirror.gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/automigrate-cloud:$SHORT_SHA"
      - "-f"
      - "docker/Dockerfile.cloud" # Fixed case
      - "."

  # --- 4. Push all three images ---
  - name: "mirror.gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/automigrate-proxy:$SHORT_SHA"]
  - name: "mirror.gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/automigrate-legacy:$SHORT_SHA"]
  - name: "mirror.gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/automigrate-cloud:$SHORT_SHA"]

  # --- 5. Deploy the PROXY service ---
  # Using the new mirrored, standard gcloud builder
  - name: "mirror.gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud # Added required entrypoint
    args:
      - "run"
      - "deploy"
      - "automigrate-proxy"
      - "--image"
      - "gcr.io/$PROJECT_ID/automigrate-proxy:$SHORT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--service-account"
      - "automigrateai-sa@automigrateai.iam.gserviceaccount.com"

  # --- 6. Deploy the LEGACY service ---
  # Using the new mirrored, standard gcloud builder
  - name: "mirror.gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud # Added required entrypoint
    args:
      - "run"
      - "deploy"
      - "automigrate-legacy"
      - "--image"
      - "gcr.io/$PROJECT_ID/automigrate-legacy:$SHORT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--service-account"
      - "automigrateai-sa@automigrateai.iam.gserviceaccount.com"

  # --- 7. Deploy the CLOUD service ---
  # Using the new mirrored, standard gcloud builder
  - name: "mirror.gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud # Added required entrypoint
    args:
      - "run"
      - "deploy"
      - "automigrate-cloud"
      - "--image"
      - "gcr.io/$PROJECT_ID/automigrate-cloud:$SHORT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--service-account"
      - "automigrateai-sa@automigrateai.iam.gserviceaccount.com"

# --- Build Configuration ---
serviceAccount: "projects/automigrateai/serviceAccounts/automigrateai-sa@automigrateai.iam.gserviceaccount.com"
options:
  logging: CLOUD_LOGGING_ONLY
