steps:
  # This step builds your Docker image
  - name: "gcr.io/cloud-builders/docker"
    # 'args' lists the commands to run
    args:
      # 'build' command
      - "build"
      # '-t' tags the image with a name
      - "-t"
      - "gcr.io/automigrateai/github.com/sandeshshinde204-bit/automigrateai:$SHORT_SHA"
      # '-f' points to the exact Dockerfile to use
      # This path is correct based on your screenshot
      - "-f"
      - "docker/Dockerfile.proxy"
      # '.' tells Docker to use the
      # entire root directory as the build context
      - "."

# This pushes the built image to the Google Container Registry
images:
  - "gcr.io/automigrateai/github.com/sandeshshinde204-bit/automigrateai:$SHORT_SHA"

# This specifies the custom service account for the build
serviceAccount: "projects/automigrateai/serviceAccounts/automigrateai-sa@automigrateai.iam.gserviceaccount.com"

# This option fixes the GCS bucket permission error
# by sending logs to Cloud Logging instead
options:
  logging: CLOUD_LOGGING_ONLY
