steps:
  # STEP 1: Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/automigrateai/github.com/sandeshshinde204-bit/automigrateai:$SHORT_SHA"
      - "-f"
      - "docker/Dockerfile.proxy"
      - "."

  # STEP 2: Push the container image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/automigrateai/github.com/sandeshshinde204-bit/automigrateai:$SHORT_SHA",
      ]

  # STEP 3: Deploy the container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      # This will be your service name in Cloud Run
      - "automigrateai-service"
      # This is the image we just built and pushed
      - "--image"
      - "gcr.io/automigrateai/github.com/sandeshshinde204-bit/automigrateai:$SHORT_SHA"
      # This uses the region from your build log
      - "--region"
      - "us-central1"
      # This makes your service public on the internet
      - "--allow-unauthenticated"
      # This uses the same service account for the deployed app
      - "--service-account"
      - "automigrateai-sa@automigrateai.iam.gserviceaccount.com"

# This section is now handled by Step 2
images:
  - "gcr.io/automigrateai/github.com/sandeshshinde204-bit/automigrateai:$SHORT_SHA"

# This specifies the service account for the build *itself*
serviceAccount: "projects/automigrateai/serviceAccounts/automigrateai-sa@automigrateai.iam.gserviceaccount.com"

# This option fixes the GCS bucket permission error
options:
  logging: CLOUD_LOGGING_ONLY
